# Generated by Django 3.1.5 on 2021-02-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Muscel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Muscel_name', models.CharField(max_length=60)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workoutPlan.days')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=70)),
                ('reps', models.IntegerField(max_length=20)),
                ('sets', models.IntegerField(max_length=10)),
                ('muskel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muskel', to='workoutPlan.muscel')),
            ],
        ),
    ]
