# Generated by Django 3.1.5 on 2021-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutPlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='day_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(),
        ),
    ]
