# Generated by Django 3.1.5 on 2021-02-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutPlan', '0002_auto_20210224_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muskel',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='muscel',
            name='day',
        ),
        migrations.CreateModel(
            name='Ultra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.CharField(max_length=20)),
                ('sets', models.IntegerField()),
                ('dagen_ultra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_ultra', to='workoutPlan.days')),
                ('exercise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_name_ultra', to='workoutPlan.exercise')),
                ('muskel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muskel_ultra', to='workoutPlan.muscel')),
            ],
        ),
        migrations.CreateModel(
            name='Hard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.CharField(max_length=20)),
                ('sets', models.IntegerField()),
                ('dagen_hard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_hard', to='workoutPlan.days')),
                ('exercise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_name_hard', to='workoutPlan.exercise')),
                ('muskel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muskel_hard', to='workoutPlan.muscel')),
            ],
        ),
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.CharField(max_length=20)),
                ('sets', models.IntegerField()),
                ('dagen_basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_basic', to='workoutPlan.days')),
                ('exercise_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_name_basic', to='workoutPlan.exercise')),
                ('muskel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muskel_basic', to='workoutPlan.muscel')),
            ],
        ),
    ]
